---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: home-assistant
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: home-assistant
    serviceAccount: default
