---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-dns-prod-credentials-secret
type: Opaque
data:
  secret-access-key: {{.Values.accessKeySecret | required ".Values.accessKeySecret' is required" | b64enc}}
