---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{.Values.email | required ".Values.email' is required"}}
    privateKeySecretRef:
      name: letsencrypt-dns-prod
    solvers:
      - selector:
        dnsZones:
          - {{.Values.domain | required ".Values.domain' is required"}}
        dns01:
          route53:
            region: {{.Values.region | required ".Values.region' is required"}}
            hostedZoneID: {{.Values.hostedZoneID | required ".Values.hostedZoneID' is required"}}
            accessKeyID: {{.Values.accessKeyID | required ".Values.accessKeyID' is required"}}
            secretAccessKeySecretRef:
              name: letsencrypt-dns-prod-credentials-secret
              key: secret-access-key
