---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: nixys
    url: https://registry.nixys.ru/chartrepo/public
  - name: victoriametrics
    url: https://victoriametrics.github.io/helm-charts/

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    values:
      - values-ingress-nginx.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.12.3
    set:
      - name: installCRDs
        value: true

  - name: victoriametrics-auth
    namespace: victoriametrics
    chart: victoriametrics/victoria-metrics-auth
    version: 0.3.2
    values:
      - secretName: "victoriametrics-auth-config-config"
      - serviceMonitor:
          enabled: true
      - resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-dns-prod"
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,192.168.1.0/24"
          hosts:
            - name: victoriametrics.{{ requiredEnv "DOMAIN" }}
              path: /
              pathType: ImplementationSpecific
          tls:
            - secretName: victoriametrics-general-tls
              hosts:
                - victoriametrics.{{ requiredEnv "DOMAIN" }}

  - name: victoriametrics-auth-config
    namespace: victoriametrics
    chart: nixys/universal-chart
    version: 2.4.0
    values:
      - secrets:
          config:
            enabled: true
            data:
              auth.yml: |
                users:
                  - bearer_token: "XXXX"
                    url_prefix: "http://victoriametrics-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428"

                  - bearer_token: "homekit"
                    url_prefix: "http://victoriametrics-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428?extra_label=category=homekit"

                  - username: "test"
                    password: "test"
                    url_prefix: "http://victoriametrics-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428"


  - name: victoriametrics
    namespace: victoriametrics
    chart: victoriametrics/victoria-metrics-single
    version: 0.9.2
    values:
      - server:
          serviceMonitor:
            enabled: true
          retentionPeriod: 36
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      - vmstorage:
          persistentVolume:
            storageClass: "local-path"
            size: "50Gi"

  - name: cert-manager-cluster-issuer
    namespace: cert-manager
    chart: ./cert-manager-cluster-issuer
    values:
      - values-cert-manager-cluster-issuer.yaml

  - name: kube-prometheus-stack
    namespace: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 48.2.2
    values:
      - values-kube-prometheus-stack.yaml.gotmpl

  # This will be autodetected by the kube-prometheus-stack
  - name: grafana-dashboards
    namespace: grafana-dashboards
    chart: nixys/universal-chart
    version: 2.4.0
    values:
      - grafana-dashboards.yaml.gotmpl
