---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: nixys
    url: https://registry.nixys.ru/chartrepo/public
  - name: victoria-metrics
    url: https://victoriametrics.github.io/helm-charts/
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    values:
      - values-ingress-nginx.yaml

  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.25.0
    values:
      - values-vault.yaml.gotmpl

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.12.3
    set:
      - name: installCRDs
        value: true

  - name: victoria-metrics-auth
    namespace: victoria-metrics
    chart: victoria-metrics/victoria-metrics-auth
    version: 0.3.2
    values:
      - values-victoria-metrics-auth.yaml.gotmpl

  - name: victoria-metrics
    namespace: victoria-metrics
    chart: victoria-metrics/victoria-metrics-single
    version: 0.9.2
    values:
      - values-victoria-metrics-single.yaml

  - name: cert-manager-cluster-issuer
    namespace: cert-manager
    chart: ./cert-manager-cluster-issuer
    values:
      - values-cert-manager-cluster-issuer.yaml

  - name: kube-prometheus-stack
    namespace: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 48.2.2
    values:
      - values-kube-prometheus-stack.yaml.gotmpl

  # This will be autodetected by the kube-prometheus-stack
  - name: grafana-dashboards
    namespace: grafana-dashboards
    chart: nixys/universal-chart
    version: 2.4.0
    values:
      - grafana-dashboards.yaml.gotmpl
