---
secrets:
  config:
    enabled: true
    data:
      auth.yml: |
        users:
          - bearer_token: "XXXX"
            url_prefix: "http://victoriametrics-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428"

          - bearer_token: "homekit"
            url_prefix: "http://victoriametrics-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428?extra_label=category=homekit"

          - username: "test"
            password: "test"
            url_prefix: "http://victoriametrics-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428"
