---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-credentials
spec:
  type: kv-v2
  mount: kvv2
  path: kube-prometheus-stack/grafana-admin-credentials
  destination:
    name: grafana-admin-credentials
    create: true
  vaultAuthRef: grafana
