---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: prometheus
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: kube-prometheus-stack-prometheus
    serviceAccount: kube-prometheus-stack-prometheus
