---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: longhorn-ingress-basic-auth
spec:
  type: kv-v2
  mount: kvv2
  path: longhorn/ingress-basic-auth
  destination:
    name: longhorn-ingress-basic-auth
    create: true
  vaultAuthRef: longhorn
