---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: longhorn
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: longhorn
    serviceAccount: longhorn-service-account
