---
repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts
  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts
  - name: minio
    url: https://charts.min.io/

releases:
  - name: homebridge
    namespace: homebridge
    chart: k8s-at-home/homebridge
    version: 5.3.2
    values:
      - values/homebridge.yaml.gotmpl

  - name: pacoloco
    namespace: pacoloco
    chart: bjw-s/app-template
    version: 1.5.1
    values:
      - values/pacoloco.yaml.gotmpl

  - name: tgtg-enhancements
    namespace: tgtg
    chart: ./charts/tgtg-enhancements

  - name: tgtg
    namespace: tgtg
    chart: bjw-s/app-template
    version: 1.5.1
    values:
      - values/tgtg.yaml.gotmpl

  - name: home-assistant-enhancements
    namespace: home-assistant
    chart: ./charts/home-assistant-enhancements

  - name: home-assistant
    namespace: home-assistant
    chart: bjw-s/app-template
    version: 1.5.1
    values:
      - values/home-assistant.yaml.gotmpl

  - name: minio-enhancements
    namespace: minio
    chart: ./charts/minio-enhancements

  - name: minio
    namespace: minio
    chart: minio/minio
    version: 5.0.13
    values:
      - values/minio.yaml.gotmpl
