---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tgtg-username
spec:
  type: kv-v2
  mount: kvv2
  path: services/tgtg/username
  destination:
    name: tgtg-username
    create: true
  vaultAuthRef: tgtg
