---
all:
  hosts:
    homeserver:
      ansible_connection: ssh
      ansible_user: server
      ansible_host: homeserver.lan
  vars:
    k3s_become: true
    cleanup_bootstrap_user: false
    upgrade_packages: false
    timezone: Europe/Warsaw
