---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-root-credentials
spec:
  type: kv-v2
  mount: kvv2
  path: services/minio/core/root-credentials
  destination:
    name: minio-root-credentials
    create: true
  vaultAuthRef: minio
